bankproject/bank/bank/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankproject/bank/bankapp/urls.py
from django.urls import path
from .import views
app_name = 'bankapp'
urlpatterns =[
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('form/', views.form, name='form'),
    path('application/', views.application,name='application'),
    path('logout/',views.logout, name='logout'),
]

bankproject/bank/bankapp/models.py
from django.db import models

# Create your models here.

bankproject/bank/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


def home(request):
    return render(request,'home.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('bankapp:form')
        else:
            context = {
                'error':True,
                'message':'Invalid Credentials'
            }
            return render(request,'login.html',context)
    return render(request,'login.html')

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['confirm_password']
        if password == cpassword:
            if User.objects.filter(username=username).exists():
                context ={
                    'error' :True,
                    'message': 'Username Already exists'
                }
                return render(request,'register.html',context)
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                return redirect('bankapp:login')
        else:
            context={
                'error':True,
                'message':'Password not matching'
            }
            return render(request,'register.html',context)
        return redirect('/')
    return render(request,'register.html')
def form(request):
    return render(request,'form.html')
def application(request):
    return render(request,'application.html')
def logout(request):
    auth.logout(request)
    return redirect('bankapp:home')

bankproject/bank/templates/application.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application accepted</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <style>
        body {
        background-color:#f2f2f2;
        font-family: Ariel,sans-serif;
        }
        .container {
        margin-top: 50px;
        }
        .jumbotron {
        background-color:#5cb85c;
        color: #fff;
        }
        .btn {
        backgrount-color: #4CAF50;
        color: #fff;
        border: none;
        }
        .btn:hover {
        background-color: #3e8e41;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="jumbotron text-center">
        <h1>The application has been submitted</h1>
        <p>congratulations!!</p>
        <button class="btn btn-lg" onclick="window.location.href='{% url 'bankapp:form' %}"></button>
    </div>
    <div class="logout-button">
         <a href="{% url 'bankapp:login' %}">Logout</a>
     </div>
</div>
</body>
</html>

bankproject/bank/templates/click.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submit button Example</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
 <div class="container mt-5">
     <h1>Submit button Example</h1>
     <p>Click the button below</p>
     <button type="button" class="btn btn-primary" onclick="showMessage()">Submit</button>
 </div>
<script>
    function showMessage() {
    alert("Application accepted");
    }
</script>
</body>
</html>

bankproject/bank/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Form</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <style>
        body{
        background-color:Purple;
        }
        .form-container{
         margin-top:50px;
         max-width:500px;
         padding:20px;
         background-color:#fff;
         border-radius:5px;
         margin:0 auto;
         box-shadow:0px 2px 10px rgba(0,0,0,0.3);
        }
        .form-group{
         margin-bottom:20px;
        }
        .form-group label {
         display:block;
         margin-bottom:5px;
        }
        .form-group input,
        .form-group select,
        .form-group textarea {
         width:100%;
         border-radius:5px;
         border: 2px solid #ccc;
         padding: 10px;
         font-size: 16px;
        }
        .submit-button{
         text-align: center;
         margin-top: 20px;
        }
        .submit-button input{
         background-color:blue;
         color:#fff;
         border:none;
         border-radius: 5px;
         padding: 10px 20px;
         font-size: 16px;
         cursor: pointer;
        }

        .logout-button:hover {
         text-decoration:none;
        }
    </style>
</head>
<body>
 <div class="form-container">
     <form class="login-form" method="post" action="{% url 'bankapp:application' %}">
         {% csrf_token %}
         <h2>Registration form</h2>
         <div class="form-group">
             <label for="name">Name</label>
             <input class="form-control" type="text" id="name" name="name" required />
             <small>Enter your full name</small>
         </div>
         <div class="form-group">
             <label for="dob">Date of Birth</label>
             <input type="date" id="dob" name="dob" required>
         </div>
         <div class="form-group">
             <label for="age">Age</label>
             <input type="number" id="age" name="age" min="1" max="120" required>
         </div>
         <div class="form-group">
             <label>Gender</label>
             <div>
                 <input type="radio" id="male" name="gender" value="male">
                 <label for="male">Male</label>
             </div>
             <div>
                 <input type="radio" id="female" name="gender" value="female">
                 <label for="female">Female</label>
             </div>
             <div>
                 <input type="radio" id="other" name="gender" value="other">
                 <label for="other">Other</label>
             </div>
         </div>
         <div class="form-group">
             <label for="number">Enter phone number:</label>
             <input type="number" id="number" name="number" required>
         </div>
         <div class="form-group">
             <label for="email">Email Address</label>
             <input type="email" id="email" name="email" required>
         </div>
         <div class="form-group">
             <label for="address">Address</label>
             <textarea id="address" name="address" required></textarea>
         </div>
         <div class="form-group">
             <label for="district">District</label>
             <select id="district" name="district" onchange="populate(this.id,'branch')" required>
                 <option value="">--District--</option>
                <option value="Kollam">Kollam</option>
                <option value="Kottayam">Kottayam</option>
                <option value="Alappuzha">Alappuzha</option>
                <option value="Idukki">Idukki</option>
                <option value="Wayanad">Wayanad</option>
             </select>
         </div>
         <div class="form-group">
             <label for="branch">Branch</label>
             <select id="branch" name="branch" required>
                 <option value="">--Select Branch--</option>

             </select>
         </div>
      <div class="form-group">
             <label for="Account-type">Account Type</label>
             <select id="Account-type" name="Account-type" required>
                 <option value="">--Select Account Type--</option>
                 <option value="Savings">Savings Account</option>
                 <option value="Current">Current account</option>
                 <option value="Fixed Deposit">Fixed Deposit Account</option>
             </select>
         </div>
         <div class="form-group">
             <label>Materials Provided</label>

             <div>
                 <input type="checkbox" id="debit-card" name="materials-provided[]" value="debit-card">
                 <label for="debit-card">Debit Card</label>
             </div>
             <div>
                 <input type="checkbox" id="credit-card" name="materials-provided[]" value="credit-card">
                 <label for="credit-card">Credit Card</label>
             </div>
             <div>
                 <input type="checkbox" id="cheque-book" name="materials-provided[]" value="cheque-book">
                 <label for="cheque-book">Cheque Book</label>
             </div>
         </div>
             <div class="submit-button">
             <button type="submit" class="btn btn-primary">Submit</button>
             </div>
     </form>

 </div>
 <script>
	 function populate(s1,s2)
	 {
	 var s1 = document.getElementById(s1);
	 var s2 = document.getElementById(s2);

	 s2.innerHTML ="";

	 if(s1.value=="Kollam")
	 {
	 var optionArray=['karunagappally|Karunagappally','oachira|Oachira'];
	 }
	 else if(s1.value=="Kottayam")
	 {
	 var optionArray=['pala|Pala','pambadi|Pambadi'];
	 }
	 else if(s1.value=="Alappuzha")
	 {
	 var optionArray=['Kuttanad|Kuttanad','Cherthala|Cherthala'];
	 }
	 else if(s1.value=="Idukki")
	 {
	 var optionArray=['Kumali|Kumali','Munnar|Munnar'];
	 }
	 else if(s1.value=="Wayanad")
	 {
	 var optionArray=['Noolpuzha|Noolpuzha','Mananthavadi|Mananthavadi'];
	 }
	 for(var option in optionArray)
	 {
	 var pair=optionArray[option].split("|");
	 var newoption=document.createElement("option");

	 newoption.value=pair[0];
	 newoption.innerHTML=pair[1];
	 s2.options.add(newoption);
	 }
	 }
 </script>
</body>
</html>

bankproject/bank/templates/home.html
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.navbar {
  overflow: hidden;
  background-color: #008080;
  text-align:center;
}

.navbar a {
  float: left;
  font-size: 25px;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}
</style>
</head>
<body style="background-color:white;">
<div class="navbar-header">

<div class="navbar">
<a class="navbar-brand" style="height:90px; color: #000080" href="#"><h2>IDBI BANK</h2></a>
  <a href="login/">Login</a>
  <a href="register/">Register</a>
  <div class="dropdown">
    <button class="dropbtn">Branches
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a style="color: #230;" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a>
                    <a style="color: #230;" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a>
                    <a style="color: #230;" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a>
                    <a style="color: #230;" href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a>
                    <a style="color: #230;" href="https://en.wikipedia.org/wiki/Wayanad_district">Wayanad</a>
    </div>
  </div>
</div>
</div>
<a href="login/">
      <input type="submit"/>
     </a>
</body>
</html>

bankproject/bank/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
   <style>
       .container {
           margin-top: 5%;
           background-color: #a2a2d0;
           border-radius: 10px;
           box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
           padding: 30px;
          }
   </style>
</head>
 <body>
   <div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <form class="login-form" action="{% url 'bankapp:login' %}" method="post">
                {% csrf_token %}
                <h2>Login</h2>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                {% if error %}
                <small style="color:red">{{message}}</small>
                {% endif %}
                <button type="submit" class="btn btn-success">Submit</button>
                <div class="register-link">Don't have an account? <a href="{% url 'bankapp:register' %}">Register here</a></div>
            </form>
        </div>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!--<h2>Login</h2>-->
<!--<form action="login" method="post">-->
<!--       {% csrf_token %}-->
<!--       <input type="text" name="username" placeholder="Enter your username"><br>-->
<!--       <input type="password" name="password" placeholder="Enter your password"><br>-->
<!--       <input type="submit">-->
<!--</form>-->
</body>
</html>

bankproject/bank/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bankproject/bank/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration page</title>
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
     <style>
         .body {
          font-family:'Poppins', 'Gadugi';
          background-color: #0077be ;
          }
          .container {
           margin-top: 5%;
           background-color: #89cff0;
           border-radius: 10px;
           box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
           padding: 30px;
          }
          h1 {
          text-align: center;
          margin-bottom: 30px;
          }
          form {
           max-width:400px;
           margin: 0 auto;
          }
          label {
           font-weight:600;
          }
          input[type="text"], input[type="password"] {
           background-color: #f8f8f8;
           border:none;
           border-radius: 5px;
           padding: 10px;
           margin-bottom: 20px;
           width:100%;
           }
           input[type="submit"] {
            background-color: #0000ff;
            color: #fff;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.2s ease;
           }
           input[type="submit"]:hover {
            background-color: #c70039;
           }
           .login-link {
            text-align: center;
            margin-top: 20px;
           }
           .login-link a {
            color: #0000ff;
            text-decoration: none;
           }
           .login-link a:hover {
            color: #900c3f;
            text-decoration: underline;
           }
    </style>
</head>
<body>
<div class="container">
<h2>Registration</h2>
<form action="{% url 'bankapp:register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username:</label>
        <input type="text" class="form-control" id="username" name="username" required>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
    <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <div class="form-group">
        <label for="confirm_password">Confirm_Password:</label>
    <input type="password" class="form-control" id="confirm_password" name="confirm_password">
    </div>
    {% if error %}
    <small style="color:red">{{message}}</small>
    {% endif %}
    <input type="submit" value="Register">
</form>
    <div class="login-link">
        Already have an account? <a href="{% url 'bankapp:login' %}">Log in</a>
    </div>
</div>
</body>
</html>